#Use a different port
#Port 2222

PermitRootLogin no

# only after ssh keys have been made
PasswordAuthentication no

# Limit who can SSH in
#AllowUsers admin

#bet yet allow only members of a certain group
#AllowGroups sshusers

