alias ..='cd ..'
alias c='clear'
alias chmod='chmod -v'
alias cp='cp -v'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias ls='ls --color=auto'
alias mv='mv -v'
alias please='sudo'
alias py='python3'
alias python='python3'
alias rm='rm -i'
alias bat='bat --paging=never'
alias venv='source /home/abc/Utilities/myenv/bin/activate'
alias ~='cd ~'
alias notes='marktext /home/abc/Documents/configuration/notes.md'
alias pip='/home/abc/Utilities/scripts/pip_wrapper.sh'

alias test='clear'
alias anothertest='clear'
