#all aliases in different systems
alias ..='cd ..'
alias c='clear'
alias chmod='chmod -v'
alias cp='cp -v'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias ls='ls --color=auto'
alias mv='mv -v'
alias please='sudo'
alias py='python3'
alias python='python3'
alias rm='rm -i'
alias ~='cd ~'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias files='xdg-open .'
alias bat='batcat'
alias rsync='rsync -v'
#alias jelly-logs='journalctl CONTAINER_NAME=goofy_heisenberg -f'
alias jelly-logs='docker logs -f jellyfin'


#debian specific aliases
alias venv='source /home/abc/Utilities/myenv/bin/activate'
#alias notes='marktext /home/abc/Documents/configuration/notes.md'
#alias pip='/home/abc/Utilities/scripts/pip_wrapper.sh'

#termux specific
#alias notes='cdl /data/data/com.termux/files/home/storage/shared/Documents/configuration'
