#!/bin/bash

# Get the selected file or directory path from Nautilus
DIR_PATH=$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)

notify-send -i  mkvtoolnix-gui "MKVToolNix" "Opening: $DIR_PATH in MKVToolNix"

# Open mkvtoolnix-gui with the selected file
mkvtoolnix-gui "$DIR_PATH"
