#!/bin/bash

# Get the selected file or directory path from Nautilus
DIR_PATH=$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)

notify-send -i  vstudio "Visual Studio Code" "Opening: $DIR_PATH in Visual Studio Code"

# Open Visual Studio Code with the selected file or directory
code "$DIR_PATH"
