#!/bin/bash

# Get the selected file or directory path from Nautilus
DIR_PATH=$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)

# Copy the path to the clipboard using xclip
echo -n "$DIR_PATH" | xclip -selection clipboard

# Notify the user
notify-send -i edit-copy "Path copied to clipboard" "$DIR_PATH"
