#!/bin/bash

#Must be a directory
# Get the selected file or directory path from Nautilus
DIR_PATH=$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | head -n 1)

# Open Baobab with the selected directory
baobab "$DIR_PATH"
